### ISSUE TITLE
Error: "Function called outside component initialization"

### ISSUE THREAD

**Issue by arrowtype** [Glench/sveltekit-github-pages-template#2]
Hi, thanks so much for making this template! It seems very promising, but... it isn’t currently working for me locally.

When I clone it, npm install, and then try `npm run dev`, I get the following traceback:

```
Function called outside component initialization
Error: Function called outside component initialization
    at get_current_component (/node_modules/svelte/internal/index.mjs:948:15)
    at Module.setContext (/node_modules/svelte/internal/index.mjs:978:5)
    at root.svelte:14:1
    at $$render (/node_modules/svelte/internal/index.mjs?v=207ba33f:1742:22)
    at Object.render (/node_modules/svelte/internal/index.mjs?v=207ba33f:1750:26)
    at render_response (file:///Users/stephennixon/code/svelte-static-test/node_modules/@sveltejs/kit/dist/chunks/index.js:610:28)
    at async respond$1 (file:///Users/stephennixon/code/svelte-static-test/node_modules/@sveltejs/kit/dist/chunks/index.js:1408:4)
    at async render_page (file:///Users/stephennixon/code/svelte-static-test/node_modules/@sveltejs/kit/dist/chunks/index.js:1487:19)
    at async resolve (file:///Users/stephennixon/code/svelte-static-test/node_modules/@sveltejs/kit/dist/chunks/index.js:1641:10)
    at async respond (file:///Users/stephennixon/code/svelte-static-test/node_modules/@sveltejs/kit/dist/chunks/index.js:1607:20)
Function called outside component initialization
Error: Function called outside component initialization
    at get_current_component (/node_modules/svelte/internal/index.mjs:948:15)
    at Module.setContext (/node_modules/svelte/internal/index.mjs:978:5)
    at root.svelte:14:1
    at $$render (/node_modules/svelte/internal/index.mjs?v=207ba33f:1742:22)
    at Object.render (/node_modules/svelte/internal/index.mjs?v=207ba33f:1750:26)
    at render_response (file:///Users/stephennixon/code/svelte-static-test/node_modules/@sveltejs/kit/dist/chunks/index.js:610:28)
    at async respond_with_error (file:///Users/stephennixon/code/svelte-static-test/node_modules/@sveltejs/kit/dist/chunks/index.js:1174:10)
    at async respond$1 (file:///Users/stephennixon/code/svelte-static-test/node_modules/@sveltejs/kit/dist/chunks/index.js:1425:4)
    at async render_page (file:///Users/stephennixon/code/svelte-static-test/node_modules/@sveltejs/kit/dist/chunks/index.js:1487:19)
    at async resolve (file:///Users/stephennixon/code/svelte-static-test/node_modules/@sveltejs/kit/dist/chunks/index.js:1641:10)
```

When I try `npm run build`, I get this:

```
vite v2.9.15 building for production...
✓ 12 modules transformed.
[vite:resolve] Missing "./preload-helper" export in "vite" package
> Missing "./preload-helper" export in "vite" package
    at bail (/Users/stephennixon/code/svelte-static-test/node_modules/@sveltejs/kit/node_modules/vite/dist/node/chunks/dep-689425f3.js:38597:8)
    at resolve (/Users/stephennixon/code/svelte-static-test/node_modules/@sveltejs/kit/node_modules/vite/dist/node/chunks/dep-689425f3.js:38674:10)
    at resolveExports (/Users/stephennixon/code/svelte-static-test/node_modules/@sveltejs/kit/node_modules/vite/dist/node/chunks/dep-689425f3.js:40982:12)
    at resolveDeepImport (/Users/stephennixon/code/svelte-static-test/node_modules/@sveltejs/kit/node_modules/vite/dist/node/chunks/dep-689425f3.js:41000:31)
    at tryNodeResolve (/Users/stephennixon/code/svelte-static-test/node_modules/@sveltejs/kit/node_modules/vite/dist/node/chunks/dep-689425f3.js:40773:20)
    at Object.resolveId (/Users/stephennixon/code/svelte-static-test/node_modules/@sveltejs/kit/node_modules/vite/dist/node/chunks/dep-689425f3.js:40581:28)
    at /Users/stephennixon/code/svelte-static-test/node_modules/@sveltejs/kit/node_modules/rollup/dist/shared/rollup.js:22826:37
```

I’ve updated to node v18.12.0, but the problem persists.

Should I try something else? No big pressure; I just wanted to reach out in case seeing these tracebacks might be useful to you.

Cheers!

**Comment by Glench** [comment]
Hm, thanks for the bug report. I made [this issue](https://github.com/sveltejs/kit/issues/7417) on SvelteKit to try to get to the bottom of the problem.

**Comment by arrowtype** [comment]
Okay, thanks so much for digging deeper, and thanks for filing the issue with SvelteKit!

I found another solution to my immediate problem of getting a static sveltekit site onto GH-Pages, so this isn’t blocking me, but from your issue report, it definitely seems like it would be a good thing to get solved overall.
